### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/JJJ#1]
- [x] Project proposal [p-proposal](due Thu Oct 26)
- [x] Project progress report [p-progress](due Thu Nov 16)
- [x] Project poster session [p-poster](due Mon Dec 4)
- [x] Project poster session (peer review) [p-peer](due Tue Dec 5)
- [x] Project final report [p-final](due Fri Dec 15)

**Comment by jennykim1016** [comment]
Done
