### ISSUE TITLE
To-do list Monday night

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/JJJ#5]
- [x] Janel: Naive Bayes Algorithm for the baseline
- [x] Jenny: Linear SVM for the baseline
- [x] James: Come up with an algorithm (Hansohl suggested to use RNN (time-series)) and think of a way to use it (should be able to feed the data in and get the results I think)

**Comment by jennykim1016** [comment]
Also done
